name: melos_rack_workspace
publish_to: none

repository: https://github.com/coolosos/wildness_ui
issue_tracker: https://github.com/coolosos/wildness_ui/issues
homepage: https://github.com/coolosos

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">3.32.0"

workspace:
  - packages/wildness_ui
  - packages/wildness_ui_golden_toolkit

dev_dependencies:
  melos: ^7.4.0
  coolint: 2.1.2

melos:
  scripts:
    analyze:
      description: Analyze all packages
      run: dart analyze .

    test:
      description: Run tests in all packages
      run: dart test

    format:
      description: Format all packages
      run: dart format .