name: melos_rack_workspace
publish_to: none

repository: https://github.com/coolosos/wildness_ui
issue_tracker: https://github.com/coolosos/wildness_ui/issues
homepage: https://github.com/coolosos

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.6"

dev_dependencies:
  melos: ^6.3.2
  coolint: 2.0.1
