name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  wildness_ui_golden_toolkit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 2.1.2

flutter:
  uses-material-design: true
