name: wildness_ui_golden_toolkit
description: "A tools for create golden test on wildness components."

repository: https://github.com/coolosos/wildness_ui
issue_tracker: https://github.com/coolosos/wildness_ui/issues
homepage: https://github.com/coolosos

version: 1.1.0

environment:
  sdk: ">=3.13.2 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.19.0
  collection: ^1.19.1
  equatable: ^2.1.0
  nested: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.16.0

  wildness_ui: ^1.1.0

dev_dependencies:
  coolint: ^3.0.0-rc.1

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/wildness_ui_golden_toolkit/fonts/Roboto-Regular.ttf
