name: wildness_ui_golden_toolkit
description: "Tools for creating golden tests on Wildness UI components."

repository: https://github.com/coolosos/wildness_ui
issue_tracker: https://github.com/coolosos/wildness_ui/issues
homepage: https://github.com/coolosos

version: 2.0.0-rc.2

environment:
  sdk: ">=3.13.2 <4.0.0"
  flutter: ">=3.47.2"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.19.0
  collection: ^1.19.1
  flutter_test:
    sdk: flutter

  wildness_ui: ^2.0.0-rc.2

dev_dependencies:
  coolint: ^3.0.0-rc.1

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/wildness_ui_golden_toolkit/fonts/Roboto-Regular.ttf
