name: wildness_ui_example
description: "Demonstration and example app for Wildness UI theming engine."
publish_to: "none"
version: 2.0.0-rc.1

environment:
  sdk: ">=3.13.2 <4.0.0"
  flutter: ">=3.47.2"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  wildness_ui: ^2.0.0-rc.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 3.0.0-rc.1

flutter:
  uses-material-design: true
