name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  FLUTTER_VERSION: 3.19.6
  MELOS_VERSION: 6.0.0
  RUNID: ${{ github.run_number }}
  TAG: ${{ github.ref_name }}
 

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
 
      # - name: 🎯 Setup Dart
      #   uses: dart-lang/setup-dart@v1
      #   with:
      #     sdk: stable

      - name: 🎯 Setup flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: false

      - name: Melos action
        uses: bluefireteam/melos-action@v3
        with:
          melos-version: ${{ env.MELOS_VERSION }}
          run-bootstrap: true

      - run: melos publish --no-dry-run